#!/usr/bin/env python3
"""
labs/L7/teacher_store_contract.py
教师缓存元数据检查与假设存储账（不保存隐藏张量，不测吞吐）

针对离线特征预生成 (Offline Pre-computation) 与 在线共置生产 (Online Co-located Serving) 建立契约：
1. 教师特征缓存条目数据结构 (Schema):
   - Sample ID, Token Sequence Hash, Teacher Model Revision, Layer Indices, Hidden Tensors, Mask, Created Timestamp
2. 缓存一致性与失效拦截 (Cache Validation & Eviction Counterexamples):
   - 反例 1 (Revision Mismatch): 教师模型迭代更新后，旧缓存特征被判定过期并拒绝读取
   - 反例 2 (Template Mismatch): 会话模板微调导致 Token 长度或切分分叉，哈希校验阻断静默错误
3. 全词表 Logits vs 隐层特征 (Hidden States) 存储与传输网络账本 (100K 样本规模):
   - 全词表 Logits (V=152,064) 产生的 TB 级存储爆炸
   - 隐层特征压缩存储 (EAGLE3 / SpecForge 方案) 的容量节约量化 (25x~50x)
"""

import hashlib
import json
import os
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class TeacherFeatureRecord:
    sample_id: str
    token_hash: str
    seq_length: int
    teacher_revision: str
    extracted_layers: List[int]
    hidden_dim: int
    dtype: str  # "fp16", "bf16", "fp8"
    storage_bytes: int
    created_at: float


class TeacherFeatureStore:
    """元数据示例；没有 tensor payload、ACK 队列或恢复实现。"""

    def __init__(self, current_teacher_revision: str):
        self.current_teacher_revision = current_teacher_revision
        self.store: Dict[str, TeacherFeatureRecord] = {}

    def put(
        self,
        sample_id: str,
        token_ids: List[int],
        extracted_layers: List[int],
        hidden_dim: int,
        dtype: str = "bf16",
    ) -> TeacherFeatureRecord:
        token_str = ",".join(map(str, token_ids))
        token_hash = hashlib.sha256(token_str.encode("utf-8")).hexdigest()
        bytes_per_elem = 1 if dtype == "fp8" else 2
        total_bytes = len(token_ids) * hidden_dim * len(extracted_layers) * bytes_per_elem

        record = TeacherFeatureRecord(
            sample_id=sample_id,
            token_hash=token_hash,
            seq_length=len(token_ids),
            teacher_revision=self.current_teacher_revision,
            extracted_layers=extracted_layers,
            hidden_dim=hidden_dim,
            dtype=dtype,
            storage_bytes=total_bytes,
            created_at=time.time(),
        )
        self.store[sample_id] = record
        return record

    def get(
        self, sample_id: str, current_token_ids: List[int]
    ) -> Tuple[bool, str, Optional[TeacherFeatureRecord]]:
        if sample_id not in self.store:
            return False, "CacheMiss: Sample ID not found in feature store", None

        record = self.store[sample_id]

        # 校验 1：教师版本一致性
        if record.teacher_revision != self.current_teacher_revision:
            return (
                False,
                f"StaleCacheError: Feature generated by revision {record.teacher_revision}, current teacher is {self.current_teacher_revision}",
                None,
            )

        # 校验 2：Token 序列与模板一致性
        token_str = ",".join(map(str, current_token_ids))
        current_hash = hashlib.sha256(token_str.encode("utf-8")).hexdigest()
        if current_hash != record.token_hash:
            return (
                False,
                f"TokenMismatchError: Token sequence changed (hash mismatch), template or tokenizer altered",
                None,
            )

        return True, "CacheHit: Verified feature valid", record


def compute_logits_vs_hidden_storage_ledger(num_samples: int = 100_000) -> Dict[str, Any]:
    """
    计算 100K 样本在两种蒸馏路径下的存储与网络传输账本：
    - 方案 A (Logit KD): 全词表对数几率 (Qwen 词表 V = 152,064)
    - 方案 B (Feature KD): 提取 3 层隐层特征 (d = 4096, BF16 或 FP8)
    """
    seq_len = 2048
    vocab_size = 152_064
    hidden_dim = 4096
    num_layers = 3

    # 1. 全词表 Logits (BF16 = 2 bytes)
    bytes_per_sample_logits = seq_len * vocab_size * 2
    gb_per_sample_logits = bytes_per_sample_logits / (1024**3)
    total_tb_logits = (bytes_per_sample_logits * num_samples) / (1024**4)

    # 2. 隐层特征 BF16 (3 层 * 4096 * 2 bytes)
    bytes_per_sample_hidden_bf16 = seq_len * hidden_dim * num_layers * 2
    gb_per_sample_hidden_bf16 = bytes_per_sample_hidden_bf16 / (1024**3)
    total_tb_hidden_bf16 = (bytes_per_sample_hidden_bf16 * num_samples) / (1024**4)

    # 3. 隐层特征 FP8 (3 层 * 4096 * 1 byte)
    bytes_per_sample_hidden_fp8 = seq_len * hidden_dim * num_layers * 1
    total_tb_hidden_fp8 = (bytes_per_sample_hidden_fp8 * num_samples) / (1024**4)

    return {
        "num_samples": num_samples,
        "sequence_length": seq_len,
        "vocab_size": vocab_size,
        "hidden_dim": hidden_dim,
        "num_feature_layers": num_layers,
        "full_vocab_logits": {
            "bytes_per_sample_mib": round(bytes_per_sample_logits / (1024**2), 2),
            "total_storage_tib": round(total_tb_logits, 2),
            "scope": "假设形状的存储乘法，不表示已生成这些数据或已测 I/O",
        },
        "hidden_states_bf16": {
            "bytes_per_sample_mib": round(bytes_per_sample_hidden_bf16 / (1024**2), 2),
            "total_storage_tib": round(total_tb_hidden_bf16, 2),
            "savings_ratio_vs_logits": round(total_tb_logits / total_tb_hidden_bf16, 1),
            "scope": "隐藏特征占用估算；仍需词表投影时不能据此推断训练加速",
        },
        "hidden_states_fp8": {
            "bytes_per_sample_mib": round(bytes_per_sample_hidden_fp8 / (1024**2), 2),
            "total_storage_tib": round(total_tb_hidden_fp8, 2),
            "savings_ratio_vs_logits": round(total_tb_logits / total_tb_hidden_fp8, 1),
        },
    }


def main():
    from _evidence import new_output, write_result
    output_dir = new_output("Teacher cache metadata and hypothetical storage sizes")

    print("=== 开始教师特征缓存协议与存储账本验证 ===")

    # 1. 缓存生命周期与一致性校验
    store = TeacherFeatureStore(current_teacher_revision="git-commit-a1b2c3d4")

    sample_tokens = [101, 2023, 2003, 1037, 3899, 102]
    store.put(
        sample_id="sample_001",
        token_ids=sample_tokens,
        extracted_layers=[12, 24, 36],
        hidden_dim=4096,
        dtype="bf16",
    )

    # 正常读取
    ok1, msg1, rec1 = store.get("sample_001", sample_tokens)
    print(f"\n[测试用例 1] 正常缓存命中: ok={ok1}, msg={msg1}")

    # 注入反例 1：教师版本升级
    store.current_teacher_revision = "git-commit-v2-upgrade"
    ok2, msg2, rec2 = store.get("sample_001", sample_tokens)
    print(f"[测试用例 2] 教师版本变更拦截: ok={ok2}, msg={msg2}")

    # 注入反例 2：模板/Token 序列变化
    store.current_teacher_revision = "git-commit-a1b2c3d4"  # 恢复版本
    modified_tokens = [101, 2023, 2003, 1037, 3899, 9999, 102]  # Token 改变
    ok3, msg3, rec3 = store.get("sample_001", modified_tokens)
    print(f"[测试用例 3] 样本切分歧义拦截: ok={ok3}, msg={msg3}")

    # 2. 存储与网络账本计算
    storage_ledger = compute_logits_vs_hidden_storage_ledger(num_samples=100_000)
    print("\n[测试用例 4] 100K 样本蒸馏存储账本对比:")
    print(f"  -> 全词表 Logits 存储总需求: {storage_ledger['full_vocab_logits']['total_storage_tib']} TiB ({storage_ledger['full_vocab_logits']['bytes_per_sample_mib']} MiB/样本)")
    print(f"  -> 隐层特征 BF16 存储总需求: {storage_ledger['hidden_states_bf16']['total_storage_tib']} TiB ({storage_ledger['hidden_states_bf16']['bytes_per_sample_mib']} MiB/样本, 节省 {storage_ledger['hidden_states_bf16']['savings_ratio_vs_logits']}x)")
    print(f"  -> 隐层特征 FP8 存储总需求: {storage_ledger['hidden_states_fp8']['total_storage_tib']} TiB (节省 {storage_ledger['hidden_states_fp8']['savings_ratio_vs_logits']}x)")

    report_data = {
        "cache_consistency_tests": {
            "normal_hit": {"ok": ok1, "msg": msg1},
            "revision_mismatch": {"ok": ok2, "msg": msg2},
            "token_mismatch": {"ok": ok3, "msg": msg3},
        },
        "storage_bandwidth_ledger": storage_ledger,
    }

    assert ok1 and not ok2 and not ok3
    report_data['scope'] = 'metadata-only in-memory dictionary; storage sizes are estimates; no feature tensor, I/O, ACK or performance measurement'
    write_result(output_dir, 'teacher_store_report.json', report_data,
                 {'checks': ['metadata hit', 'teacher revision', 'token hash'],
                  'real_feature_payload': False, 'GPU_execution': False}, [__file__])


if __name__ == "__main__":
    main()
